=== Ronni25/bryan_cafe_acbi/xml/menu.dtd
<!ELEMENT menu (meals, beverages)>
<!ELEMENT meals (menuItem*)>
<!ELEMENT beverages (hotBeverages, otherBeverages)>
<!ELEMENT hotBeverages (menuItem*)>
<!ELEMENT otherBeverages (menuItem*)>
<!ELEMENT menuItem (name?, size?, price, description?, imageURL?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT imageURL (#PCDATA)>

=== Ronni25/bryan_cafe_acbi/xml/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
    <meals>
        <menuItem>
            <name>Beetroot and feta salad</name>
            <price>$15.00</price>
            <description>Fresh salad.</description>
            <imageURL>images/salad.jpg</imageURL>
        </menuItem>
    </meals>

    <beverages>
        <hotBeverages>
            <menuItem>
                <name>Espresso</name>
                <size>Small</size>
                <price>$3.50</price>
                <description>Strong coffee.</description>
                <imageURL>images/coffee.jpg</imageURL>
            </menuItem>
        </hotBeverages>
        
        <otherBeverages>
            <menuItem>
                <name>Orange Juice</name>
                <price>$5.00</price>
                <description>Freshly squeezed.</description>
                <imageURL>images/juice.jpg</imageURL>
            </menuItem>
        </otherBeverages>
    </beverages>
</menu>

=== Ronni25/bryan_cafe_acbi/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
    <meals>
        <menuItem>
            <name>Beetroot and feta salad</name>
            <price>$15.00</price>
            <description>Suitable for vegetarians, made with fresh beetroot</description>
            <imageURL>images/salad.jpg</imageURL>
        </menuItem>
        
        <menuItem>
            <name>Sourdough Rye Sandwich</name>
            <price>$18.00</price>
            <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>
            <imageURL>images/salad.jpg</imageURL>
        </menuItem>
        
        <menuItem>
            <name>Spinach Pie and Salad</name>
            <price>$15.00</price>
            <description>Tasty pie with salad.</description>
            <imageURL>images/salad.jpg</imageURL>
        </menuItem>

        <menuItem>
            <name>Feta pancakes with salad</name>
            <price>$19.50</price>
            <description>Tasty pancake filled with feta and salad.</description>
            <imageURL>images/salad.jpg</imageURL>
        </menuItem>

    </meals>

    <beverages>
        <hotBeverages>
            <menuItem>
                <name>Espresso</name>
                <size>Small</size>
                <price>$3.50</price>
                <description>Strong coffee.</description>
                <imageURL>images/coffee.jpg</imageURL>
            </menuItem>

            <menuItem>
                <name>Espresso</name>
                <size>Regular</size>
                <price>$4.00</price>
                <description>Strong coffee.</description>
                <imageURL>images/coffee.jpg</imageURL>
            </menuItem>

            <menuItem>
                <name>Espresso</name>
                <size>Large</size>
                <price>$4.50</price>
                <description>Strong coffee.</description>
                <imageURL>images/coffee.jpg</imageURL>
            </menuItem>
        </hotBeverages>
        
        <otherBeverages>
            <menuItem>
                <name>Soda</name>
                <price>$3.00</price>
                <description>Freshly squeezed.</description>
                <imageURL>images/juice.jpg</imageURL>
            </menuItem>

            <menuItem>
                <name>Fresh Juice</name>
                <price>$6.00</price>
                <description>Freshly squeezed.</description>
                <imageURL>images/juice.jpg</imageURL>
            </menuItem>

            <menuItem>
                <name>Bottle water</name>
                <price>$2.00</price>
                <description>Freshly squeezed.</description>
                <imageURL>images/juice.jpg</imageURL>
            </menuItem>

        </otherBeverages>
    </beverages>
</menu>
